# Generated by Django 5.2.8 on 2025-11-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpost',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationpost',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationpost',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Furniture', 'Furniture'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donationpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donationpost',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='users.donor'),
        ),
        migrations.AlterField(
            model_name='donationpost',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donationpost',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_donations', to='users.receiver'),
        ),
        migrations.AlterField(
            model_name='donationpost',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
