# Generated by Django 5.2.8 on 2025-11-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='verified',
        ),
    ]
