# Generated by Django 5.2.8 on 2025-11-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donationpost_is_accepted_donationpost_is_requested_and_more'),
        ('users', '0009_remove_donation_image_donation_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpost',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_posts', to='users.donor'),
        ),
    ]
