# Generated by Django 5.2.8 on 2025-11-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donationpost_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationpost',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donationpost',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='ProblemReport',
        ),
        migrations.DeleteModel(
            name='DonationPost',
        ),
    ]
