# Generated by Django 5.2.5 on 2025-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_generalreview_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('ngo', 'NGO')], default='donor', max_length=10),
        ),
    ]
