# Generated by Django 5.2.5 on 2025-11-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_claimrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequest',
            old_name='requested_at',
            new_name='date_requested',
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='users.donation'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.receiver'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('collected', 'Collected'), ('expired', 'Expired')], default='Pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='claimrequest',
            unique_together={('donation', 'receiver')},
        ),
    ]
