# Generated by Django 5.2.5 on 2025-11-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_requested_at_claimrequest_date_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.AddField(
            model_name='donation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
