# Generated by Django 5.2.8 on 2025-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_donation_image_donation_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Admin confirmed NGO registration'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Admin confirmed NGO existence'),
        ),
    ]
