# Generated by Django 5.2.8 on 2025-11-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_receiver_is_confirmed_receiver_is_validated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Donor Account', 'verbose_name_plural': 'Donor Accounts'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'NGO / Receiver', 'verbose_name_plural': 'NGOs / Receivers'},
        ),
    ]
