# Generated by Django 5.2.8 on 2025-11-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_receiver_is_confirmed_receiver_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image_url',
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
