# Generated by Django 5.2.8 on 2025-11-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_claimrequest_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation request', 'verbose_name_plural': 'Donation requests'},
        ),
        migrations.AlterModelOptions(
            name='receiver',
            options={'verbose_name': 'NGO / Receiver', 'verbose_name_plural': 'NGOs / Receivers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
