# Generated by Django 5.2.8 on 2025-11-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_claimrequest_options_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
    ]
