# Generated by Django 5.2.8 on 2025-11-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ngo.ngoprofile'),
        ),
    ]
