# Generated by Django 5.2.8 on 2025-11-27 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('donor', '0002_initial'),
        ('ngo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'ordering': ['-date_requested']},
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='ngo.ngoprofile'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donor.donorprofile'),
        ),
    ]
