# Generated by Django 5.2.8 on 2025-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGOProfile',
            fields=[
                ('receiverID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=50)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
