# Generated by Django 5.2.8 on 2025-11-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='is_confirmed',
        ),
    ]
