# Generated by Django 5.2.8 on 2025-11-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_remove_ngoprofile_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='is_validated',
        ),
    ]
